### ISSUE TITLE
Etcd support (ability to run cluster without K8s)

### ISSUE THREAD

**Issue by alex-savin** [bkupidura/broker-ha#1]
Hey

Thank you for you implementation of mqtt cluster!
Is it possible to ask you add a Etcd support for the cluster members discovery to have an ability to tun a cluster without K8s

Best Regards,
Alex

**Comment by bkupidura** [comment]
@alex-savin you should be able to run `broker-ha` without K8s. There is only one requirment which is DNS SRV.
You can configure DNS SRV anywhere, using any tech which can manage SRV for you.
