### ISSUE TITLE
Image Pull Error (latest)

### ISSUE THREAD

**Issue by dadebue** [bkupidura/broker-ha#8]
Hi,

when I try to pull the latest (0.1.9) image I get an "unauthorized" error. Pulling the 0.1.8 image works just fine.

Any ideas?

BR
Marco

**Comment by bkupidura** [comment]
Hey @dadebue im using github infra as docker registry, it should work without any issue. Let me check on some nodes which dont have this image already pulled.

**Comment by bkupidura** [comment]
@dadebue i rebuild 0.1.9 tag, can you try now?

**Comment by dadebue** [comment]
Yep working like a charm 👍🏼
