### ISSUE TITLE
Share subscription support 

### ISSUE THREAD

**Issue by lichadehehehe** [bkupidura/broker-ha#9]
Hi, when the broker is clustering with other nodes, how would a shared subscription be dealt with? By keeping a topic-broker limit?

**Comment by bkupidura** [comment]
@lichadehehehe im not using shared subscriptions, so to be honest - i dont know.
My guess would be that they will simply dont work, as each `broker-ha` instance works without knowledge about other cluster members (on MQTT level).

I will definitly run some tests and think if there is any method to implement shared subscriptions, but this will take some time.

**Comment by bkupidura** [comment]
As expected, shared subscriptions currently are not working.
```
# mosquitto_sub -t '$SHARE/tmp/a' -h 10.42.2.27 -u user -P 'password' -v
a test1
a test2
a test3
# mosquitto_sub -t '$SHARE/tmp/a' -h 10.42.2.24 -u user -P 'password' -v
a test1
a test2
a test3
# mosquitto_pub -t 'a' -h 127.0.0.1 -u user -P 'password' -m 'test1'
# mosquitto_pub -t 'a' -h 127.0.0.1 -u user -P 'password' -m 'test2'
# mosquitto_pub -t 'a' -h 127.0.0.1 -u user -P 'password' -m 'test3'
```

I configured 2 clients, which connets to two instances of `broker-ha`, then send couple of message.
Every message was received on every client - no load-balacing.

When clients connects to single `broker-ha` instance - it works as expected.
